WITH REQUISITION_LINES_ALL_CUS AS (
    SELECT DISTINCT PRLA.REQUISITION_HEADER_ID AS REQUISITION_HEADER_ID_LINE,
        NVL(PRLA.PO_LINE_ID, PLA.PO_LINE_ID) AS HEADER_ID_LINE
    FROM PO_LINES_ALL PLA
        LEFT JOIN PO_HEADERS_ALL PHA ON PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
        LEFT JOIN POR_REQUISITION_LINES_ALL PRLA ON PHA.PO_HEADER_ID = PRLA.PO_HEADER_ID
        RIGHT JOIN POR_REQUISITION_HEADERS_ALL PRHA ON PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID
    WHERE PRHA.REQUISITION_NUMBER = :P_SOLICITUD
    GROUP BY PRLA.REQUISITION_HEADER_ID,
        PRLA.PO_LINE_ID,
        PLA.PO_LINE_ID
),
TOTAL_ORDER AS (
    SELECT PLA.PO_HEADER_ID AS TOTAL_HEADER,
        FCB.SYMBOL,
        CASE
            WHEN PHA.CURRENCY_CODE = 'COP' THEN NVL(SUM(ROUND(ZL.REC_TAX_AMT)), '0')
            ELSE NVL(SUM(ZL.REC_TAX_AMT), '0')
        END SUB_IVA,
        CASE
            WHEN PHA.CURRENCY_CODE = 'COP' THEN NVL(SUM(ROUND(PDA.TAX_EXCLUSIVE_AMOUNT)), '0')
            ELSE SUM(TAX_EXCLUSIVE_AMOUNT)
        END SUB_TOTAL,
        CASE
            WHEN PHA.CURRENCY_CODE = 'COP' THEN NVL(SUM(ROUND(ZL.REC_TAX_AMT)), '0') + SUM(ROUND(PDA.TAX_EXCLUSIVE_AMOUNT))
            ELSE NVL(SUM(ZL.REC_TAX_AMT), '0') + SUM(PDA.TAX_EXCLUSIVE_AMOUNT)
        END TOTAL
    FROM REQUISITION_LINES_ALL_CUS RLAC
        LEFT JOIN PO_LINES_ALL PLA ON RLAC.HEADER_ID_LINE = PLA.PO_LINE_ID
        LEFT JOIN PO_HEADERS_ALL PHA ON PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
        LEFT JOIN PO_LINE_LOCATIONS_ALL PLLA ON PLA.PO_HEADER_ID = PLLA.PO_HEADER_ID
        AND PLA.PO_LINE_ID = PLLA.PO_LINE_ID
        LEFT JOIN ZX_LINES ZL ON PLLA.LINE_LOCATION_ID = ZL.TRX_LINE_ID
        AND PHA.SEGMENT1 = ZL.TRX_NUMBER
        AND PLA.PO_HEADER_ID = ZL.TRX_ID
        AND ZL.INTERNAL_ORGANIZATION_ID = PLA.PRC_BU_ID
        AND EVENT_CLASS_CODE = 'PO_PA'
        LEFT JOIN PO_DISTRIBUTIONS_ALL PDA ON PLA.PO_LINE_ID = PDA.PO_LINE_ID
        LEFT JOIN FND_CURRENCIES_B FCB ON PHA.CURRENCY_CODE = FCB.CURRENCY_CODE
    GROUP BY PLA.PO_HEADER_ID,
        PHA.CURRENCY_CODE,
        FCB.SYMBOL
)
SELECT PLA.LINE_NUM,
    SUBSTR(INPUT_TAX_CLASSIFICATION_CODE, 19) PIVA,
    HLA_2.LOCATION_CODE AS Ubicacion,
    PLA.PO_HEADER_ID,
    NVL(TO_NUMBER(PLA.ATTRIBUTE1), 0) DSCTO,
    PHA.BILL_TO_LOCATION_ID,
    EIR.ORGANIZATION_ID,
    EIR.ITEM_NUMBER,
    (
        SELECT PRHA.REQUISITION_NUMBER
        FROM POR_REQUISITION_HEADERS_ALL PRHA
        WHERE PRHA.REQUISITION_HEADER_ID = RLAC.REQUISITION_HEADER_ID_LINE
    ) AS REQUISITION,
    (
        SELECT TOTAL
        FROM TOTAL_ORDER
        WHERE PLA.PO_HEADER_ID = TOTAL_HEADER
    ) AS TOTAL_ORDERS,
    PLA.ITEM_DESCRIPTION,
    PRLA.DESTINATION_SUBINVENTORY,
    CASE
        WHEN PRLA.SOURCE_ORGANIZATION_ID IS NULL THEN 'Proveedor'
        ELSE 'Inventario'
    END ORIGEN,
    TO_CHAR(PLLA.PROMISED_DATE, 'DD/MM/YYYY') AS PROMISED_DATE,
    NVL(ZL.REC_TAX_AMT, '0') AS IVA,
    (
        SELECT SUB_IVA
        FROM TOTAL_ORDER
        WHERE PLA.PO_HEADER_ID = TOTAL_HEADER
    ) AS SUB_IVA,
    NVL(PLA.QUANTITY, '0') AS QUANTITY,
    PHA.SEGMENT1,
    PLA.PRC_BU_ID,
    IUM.UNIT_OF_MEASURE,
    PLA.LIST_PRICE,
    GCC.SEGMENT5 AS CCO,
    PHA.CURRENCY_CODE,
    (
        SELECT SYMBOL
        FROM TOTAL_ORDER
        WHERE PLA.PO_HEADER_ID = TOTAL_HEADER
    ) AS SYMBOL,
    TAX_EXCLUSIVE_AMOUNT AS TOTAL_VALUE,
    (
        SELECT SUB_TOTAL
        FROM TOTAL_ORDER
        WHERE PLA.PO_HEADER_ID = TOTAL_HEADER
    ) AS SUB_TOTAL,
    CASE
        WHEN TO_NUMBER(PLA.ATTRIBUTE1) != 0 THEN (
            (
                SELECT SUB_TOTAL
                FROM TOTAL_ORDER
                WHERE PLA.PO_HEADER_ID = TOTAL_HEADER
            ) * TO_NUMBER(PLA.ATTRIBUTE1)
        ) / 100
        ELSE 0
    END SUB_DSCTO,
    PRDA.ATTRIBUTE1 AS MOTIVO_CUENTA,
    PRDA.ATTRIBUTE2 AS CENTRO_COSTO,
    ppa.SEGMENT1 AS PROYECTO,
    (
        SELECT LOC.SEGMENT1
        FROM INV_ONHAND_QUANTITIES_DETAIL Q,
            INV_ITEM_LOCATIONS LOC
        WHERE Q.ORGANIZATION_ID = EIR.INVENTORY_ITEM_ID
            AND Q.INVENTORY_ITEM_ID = EIR.ORGANIZATION_ID
            AND Q.LOCATOR_ID = LOC.INVENTORY_LOCATION_ID(+)
            AND Q.ORGANIZATION_ID = LOC.ORGANIZATION_ID (+)
            AND Q.SUBINVENTORY_CODE IS NOT NULL
    ) AS LOCALIZADOR
FROM PO_LINES_ALL PLA
    LEFT JOIN PO_HEADERS_ALL PHA ON PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
    LEFT JOIN HR_LOCATIONS_ALL HLA ON PHA.BILL_TO_LOCATION_ID = HLA.LOCATION_ID
    LEFT JOIN HR_LOCATIONS_ALL HLA_2 ON PHA.SHIP_TO_LOCATION_ID = HLA_2.SHIP_TO_LOCATION_ID
    AND Trim(HLA_2.SHIP_TO_SITE_FLAG) = 'Y'
    LEFT JOIN POR_REQUISITION_LINES_ALL PRLA ON PLA.PO_LINE_ID = PRLA.PO_LINE_ID
    LEFT JOIN POR_REQ_DISTRIBUTIONS_ALL PRDA ON PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID
    LEFT JOIN pjf_projects_all_b ppa ON PRDA.Pjc_Project_id = ppa.project_id
    LEFT JOIN PO_LINE_LOCATIONS_ALL PLLA ON PLA.PO_HEADER_ID = PLLA.PO_HEADER_ID
    AND PLA.PO_LINE_ID = PLLA.PO_LINE_ID
    LEFT JOIN EGP_SYSTEM_ITEMS_B EIR ON PLA.ITEM_ID = EIR.INVENTORY_ITEM_ID
    AND PLLA.SHIP_TO_ORGANIZATION_ID = EIR.ORGANIZATION_ID
    LEFT JOIN ZX_LINES ZL ON PLLA.LINE_LOCATION_ID = ZL.TRX_LINE_ID
    AND PHA.SEGMENT1 = ZL.TRX_NUMBER
    AND PLA.PO_HEADER_ID = ZL.TRX_ID
    AND ZL.INTERNAL_ORGANIZATION_ID = PLA.PRC_BU_ID
    AND EVENT_CLASS_CODE = 'PO_PA'
    LEFT JOIN INV_UNITS_OF_MEASURE IUM ON PLA.UOM_CODE = IUM.UOM_CODE
    LEFT JOIN PO_DISTRIBUTIONS_ALL PDA ON PLA.PO_LINE_ID = PDA.PO_LINE_ID
    LEFT JOIN GL_CODE_COMBINATIONS GCC ON PDA.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
    INNER JOIN REQUISITION_LINES_ALL_CUS RLAC ON PLA.PO_LINE_ID = RLAC.HEADER_ID_LINE
WHERE 1 = 1
    AND PLA.LINE_STATUS <> 'CANCELED'
ORDER BY PLA.LINE_NUM ASC