SELECT DISTINCT PRHA.REQUISITION_NUMBER Solicitud,
    PRHA.REQUISITION_HEADER_ID,
    PRHA.ATTRIBUTE1 AS TipoCompra,
    PRHA.ATTRIBUTE2 AS Area,
    (
        SELECT MEANING
        FROM fnd_lookup_values
        WHERE lookup_type = 'POR_DOCUMENT_STATUS'
            AND LANGUAGE = 'E'
            AND LOOKUP_CODE = PRHA.DOCUMENT_STATUS
    ) AS STATUS,
    CASE
        WHEN PRLA.SOURCE_ORGANIZATION_ID IS NULL THEN 'Proveedor'
        ELSE 'Inventario'
    END ORIGEN,
    (
        SELECT MEANING
        FROM fnd_lookup_values
        WHERE lookup_type = 'POR_DESTINATION_TYPE'
            AND LANGUAGE = 'E'
            AND LOOKUP_CODE = PRLA.DESTINATION_TYPE_CODE
    ) AS DESTINO,
    (
        SELECT DISTINCT PHA.SEGMENT1
        FROM PO_LINES_ALL PLA,
            PO_HEADERS_ALL PHA
        WHERE PLA.PO_HEADER_ID = PRLA.PO_HEADER_ID
            AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
        UNION ALL
        SELECT OP.HEADER_NUMBER
        FROM INV_TRANSFER_ORDER_HEADERS OP,
            INV_TRANSFER_ORDER_LINES POL
        WHERE 1 = 1
            AND OP.HEADER_ID = POL.HEADER_ID
            AND POL.REQUISITION_LINE_ID = PRLA.REQUISITION_LINE_ID
    ) AS PURCHASE_ORDER,
    PRLA.PO_HEADER_ID,
    (
        SELECT NAME
        FROM HR_ALL_ORGANIZATION_UNITS_F_VL HAOU
        WHERE HAOU.ORGANIZATION_ID = PRHA.REQ_BU_ID
    ) AS BUSINESS_UNIT,
    (
        SELECT HLA.LOCATION_CODE AS BILL_TO_LOCATION
        FROM HR_LOCATIONS_ALL HLA
        WHERE HLA.SHIP_TO_LOCATION_ID = PRLA.DELIVER_TO_LOCATION_ID
    ) AS BILL_TO_LOCATION,
    TO_CHAR(PRHA.CREATION_DATE, 'DD') AS CREATION_DD,
    TO_CHAR(PRHA.CREATION_DATE, 'MM') AS CREATION_MM,
    TO_CHAR(PRHA.CREATION_DATE, 'YYYY') AS CREATION_YEAR,
    TO_CHAR(PRHA.CREATION_DATE, 'DD-MM-YYYY') CREATDATE,
    PRHA.DESCRIPTION AS NOTE_TO_RECEIVER,
    (
        SELECT PPF.FULL_NAME
        FROM PO_ACTION_HISTORY PAH
            INNER JOIN PER_PERSON_NAMES_F_V PPF ON PAH.PERFORMER_ID = PPF.PERSON_ID
        WHERE PAH.OBJECT_TYPE_CODE = 'REQ'
            AND PAH.ACTION_CODE = 'APPROVE'
            AND PAH.OBJECT_ID = PRHA.REQUISITION_HEADER_ID
    ) APROBADOR,
    (
        SELECT TO_CHAR(SYSDATE -(5 / 24), 'DD/MON/YYYY HH:MI AM') Fecha
        FROM DUAL
    ) FECHA_IMPRESION,
    (
        SELECT PPF.FULL_NAME
        FROM PER_PERSON_NAMES_F_V PPF
        WHERE PPF.PERSON_ID = PRLA.REQUESTER_ID
    ) BUYER,
    --SOLICITANTE,
    (
        SELECT PPF.FULL_NAME
        FROM PER_PERSON_NAMES_F_V PPF
        WHERE PPF.PERSON_ID = PRHA.PREPARER_ID
    ) INTRODUCIDO_POR
FROM POR_REQUISITION_LINES_ALL PRLA,
    POR_REQUISITION_HEADERS_ALL PRHA
WHERE 1 = 1
    AND PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID (+)
    AND PRHA.REQUISITION_NUMBER = :P_SOLICITUD
