WITH SOLICITUD_COMPRA AS (
    SELECT DISTINCT PRHA.REQUISITION_NUMBER,
        PRHA.REQUISITION_HEADER_ID,
        PRHA.ATTRIBUTE1,
        PRHA.ATTRIBUTE2,
        PRHA.DOCUMENT_STATUS,
        PRLA.PO_HEADER_ID,
        PRLA.PO_LINE_ID,
        PRDA.ATTRIBUTE1 AS MOTIVO_CUENTA,
        PRDA.ATTRIBUTE2 AS CENTRO_COSTO,
        PRLA.DESTINATION_TYPE_CODE AS DESTINO,
        CASE
            WHEN PRLA.SOURCE_ORGANIZATION_ID IS NULL THEN 'Proveedor'
            ELSE 'Inventario'
        END ORIGEN,
        ppa.SEGMENT1 AS PROYECTO,
        PRLA.REQUESTER_ID,
        PRHA.PREPARER_ID
    FROM POR_REQUISITION_HEADERS_ALL PRHA,
        POR_REQUISITION_LINES_ALL PRLA,
        POR_REQ_DISTRIBUTIONS_ALL PRDA,
        pjf_projects_all_b ppa
    WHERE 1 = 1
        AND PRHA.REQUISITION_NUMBER = :P_SOLICITUD
        AND PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID
        AND PRLA.PO_HEADER_ID IS NOT NULL
        AND PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID (+)
        AND PRDA.Pjc_Project_id = ppa.project_id (+)
)
SELECT DISTINCT PLC.DISPLAYED_FIELD DOCUMENT_STATUS,
    PHA.RATE,
    PHA.COMMENTS,
    SOLI.REQUISITION_NUMBER Solicitud,
    SOLI.REQUISITION_HEADER_ID,
    SOLI.ATTRIBUTE1 AS TipoCompra,
    SOLI.ATTRIBUTE2 AS Area,
    SOLI.MOTIVO_CUENTA,
    SOLI.CENTRO_COSTO,
    SOLI.PROYECTO,
    SOLI.REQUESTER_ID,
    SOLI.PREPARER_ID,
    (
        SELECT MEANING
        FROM fnd_lookup_values
        WHERE lookup_type = 'POR_DOCUMENT_STATUS'
            AND LANGUAGE = 'E'
            AND LOOKUP_CODE = SOLI.DOCUMENT_STATUS
    ) AS STATUS,
    SOLI.ORIGEN,
    (
        SELECT MEANING
        FROM fnd_lookup_values
        WHERE lookup_type = 'POR_DESTINATION_TYPE'
            AND LANGUAGE = 'E'
            AND LOOKUP_CODE = SOLI.DESTINO
    ) AS DESTINO,
    G.PAYMENT_METHOD_NAME FORMA_PAGO,
    NVL(TO_CHAR(PLLA.NEED_BY_DATE, 'DD/MM/YYYY'), 0) AS DELIVERY_DATE,
    PHA.ATTRIBUTE2 AS TYPE_OF_PURCHASE,
    PHA.SEGMENT1 AS PURCHASE_ORDER,
    PHA.PO_HEADER_ID,
    PSV.VENDOR_NAME AS SUPPLIER_VENDOR_NAME,
    PSV.VENDOR_ID,
    PHA.SOLDTO_LE_ID,
    PHA.VENDOR_CONTACT_ID,
    PHA.BILLTO_BU_ID,
    PSV.PARTY_ID,
    PSAV.PARTY_SITE_NAME AS SUPPLIER_CITY,
    PSAV.ADDRESS1 AS SUPPLIER_ADDRESS,
    PSCV.ADMINISTRATIVE_CONTACT AS ADMIN,
    NVL(PSP.INCOME_TAX_ID, 'SIN NUMERO') AS SUPPLIER_NUMBER,
    PSAV.PHONE_COUNTRY_CODE || '(' || PSAV.PHONE_AREA_CODE || ')' || PSAV.PHONE_NUMBER AS SUPPLIER_PHONE_NUMBER,
    PSAV.FAX_CONTACT_POINT_TYPE || ' ' || PSAV.FAX_PHONE_AREA_CODE || ' ' || PSAV.FAX_PHONE_NUMBER AS SUPPLIER_FAX_NUMBER,
    Trim(PSCV.FIRST_NAME) || ' ' || Trim(PSCV.MIDDLE_NAME) || ' ' || Trim(PSCV.LAST_NAME) AS CONTACT_NAME,
    PSCV.EMAIL_ADDRESS AS CONTACT_EMAIL,
    PEA.SOLD_TO_LEGAL_ENTITY_NAME,
    LEI.LEGAL_ENTITY_IDENTIFIER,
    HAOU.NAME AS BUSINESS_UNIT,
    HLA.INTERNAL_LOCATION_CODE,
    HLA_2.LOCATION_CODE AS BILL_TO_LOCATION,
    HLA.REGION_2 AS LEGAL_ENTITY_CITY,
    HLA.TOWN_OR_CITY AS LEGAL_ENTITY_REGION,
    HLA.ADDRESS_LINE_1 AS ADDRESS_LINE_LEGAL_ENTITY,
    HLA.TELEPHONE_NUMBER_1 AS LEGAL_ENTITY_TELEPHONE_NUMBER,
    HLA_2.ADDRESS_LINE_1 AS ADDRESS_LINE_LEGAL_ENTITY_SEND,
    HLA_2.TOWN_OR_CITY AS TOWN_OR_CITY_LEGAL_ENTITY,
    HLA_2.REGION_2 AS REGION_LEGAL_ENTITY,
    FTVL.NLS_TERRITORY AS NLS_TERRITORY_LEGAL_ENTITY,
    PHA.BILL_TO_LOCATION_ID,
    TO_CHAR(PHA.CREATION_DATE, 'DD') AS CREATION_DD,
    TO_CHAR(PHA.CREATION_DATE, 'MM') AS CREATION_MM,
    TO_CHAR(PHA.CREATION_DATE, 'YYYY') AS CREATION_YEAR,
    TO_CHAR(PHA.CREATION_DATE, 'DD-MM-YYYY') CREATDATE,
    PHA.CURRENCY_CODE,
    FVVTL.DESCRIPTION AS CURRENCY_DESC,
    (
        SELECT PPF.DISPLAY_NAME
        FROM PO_AGENT_ACCESSES PAA,
            PER_PERSON_NAMES_F_V PPF
        WHERE PHA.AGENT_ID = PAA.AGENT_ID
            AND PHA.AGENT_ID = PPF.PERSON_ID
            AND ACCESS_ACTION_CODE = 'MANAGE_PURCHASE_ORDERS'
    ) AS BUYER,
    ATTL.NAME AS PAYMENT_TERMS,
    PHA.COMMENTS AS NOTE_TO_RECEIVER,
    (
        SELECT PPF.FULL_NAME
        FROM PO_ACTION_HISTORY PAH
            INNER JOIN PER_PERSON_NAMES_F_V PPF ON PAH.PERFORMER_ID = PPF.PERSON_ID
        WHERE PAH.OBJECT_TYPE_CODE = 'REQ'
            AND PAH.ACTION_CODE = 'APPROVE'
            AND PAH.OBJECT_ID = SOLI.REQUISITION_HEADER_ID
    ) APROBADOR,
(
        SELECT TO_CHAR(SYSDATE -(5 / 24), 'DD/MON/YYYY HH:MI AM') Fecha
        FROM DUAL
    ) FECHA_IMPRESION,
    (
        SELECT PPF.FULL_NAME
        FROM PER_PERSON_NAMES_F_V PPF
        WHERE PPF.PERSON_ID = SOLI.REQUESTER_ID
    ) SOLICITANTE,
    (
        SELECT PPF.FULL_NAME
        FROM PER_PERSON_NAMES_F_V PPF
        WHERE PPF.PERSON_ID = SOLI.PREPARER_ID
    ) INTRODUCIDO_POR
FROM SOLICITUD_COMPRA SOLI
    LEFT JOIN PO_LINES_ALL PLA ON SOLI.PO_HEADER_ID = PLA.PO_HEADER_ID
    AND SOLI.PO_LINE_ID = PLA.PO_LINE_ID
    LEFT JOIN PO_HEADERS_ALL PHA ON PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
    INNER JOIN PO_LOOKUP_CODES PLC ON PLC.LOOKUP_TYPE = 'ORDER_STATUS'
    AND PLC.LOOKUP_CODE = PHA.DOCUMENT_STATUS
    LEFT JOIN PO_LINE_LOCATIONS_ALL PLLA ON PLA.PO_HEADER_ID = PLLA.PO_HEADER_ID
    AND PLA.PO_LINE_ID = PLLA.PO_LINE_ID
    LEFT JOIN POZ_SUPPLIERS_V PSV ON PHA.VENDOR_ID = PSV.VENDOR_ID
    LEFT JOIN POZ_SUPPLIER_SITES_V PSSV ON PSSV.VENDOR_ID = PSV.VENDOR_ID
    LEFT JOIN POZ_SUPPLIER_ADDRESS_V PSAV ON PSAV.LOCATION_ID = PSSV.LOCATION_ID
    LEFT JOIN POZ_SUPPLIERS_PII PSP ON Trim(PSV.VENDOR_ID) = Trim(PSP.VENDOR_ID)
    LEFT JOIN POZ_SUPPLIER_CONTACTS_V PSCV ON PSV.VENDOR_ID = PSCV.VENDOR_ID
    AND PHA.VENDOR_CONTACT_ID = PSCV.VENDOR_CONTACT_ID
    LEFT JOIN PO_EVENT_AUDIT PEA ON PHA.PO_HEADER_ID = PEA.PO_HEADER_ID
    AND PHA.SOLDTO_LE_ID = PEA.SOLD_TO_LEGAL_ENTITY_ID
    AND PEA.EVENT_ACTION_CODE = 'IMPLEMENTED'
    LEFT JOIN XLE_ENTITY_PROFILES LEI ON PHA.SOLDTO_LE_ID = LEI.LEGAL_ENTITY_ID
    LEFT JOIN HR_ALL_ORGANIZATION_UNITS_F_VL HAOU ON PEA.REQUISITIONING_BU_ID = HAOU.ORGANIZATION_ID
    LEFT JOIN HR_LOCATIONS_ALL HLA ON HAOU.LOCATION_ID = HLA.LOCATION_ID
    LEFT JOIN HR_LOCATIONS_ALL HLA_2 ON PHA.SHIP_TO_LOCATION_ID = HLA_2.SHIP_TO_LOCATION_ID
    AND Trim(HLA_2.SHIP_TO_SITE_FLAG) = 'Y'
    LEFT JOIN FND_TERRITORIES_VL FTVL ON HLA_2.COUNTRY = FTVL.TERRITORY_CODE
    LEFT JOIN PER_PERSON_NAMES_F PPNF ON PHA.AGENT_ID = PPNF.PERSON_ID
    AND NAME_TYPE = 'GLOBAL'
    LEFT JOIN AP_TERMS_TL ATTL ON PHA.TERMS_ID = ATTL.TERM_ID
    AND ATTL.LANGUAGE = 'E'
    LEFT JOIN FND_VS_VALUES_B FVVB ON PHA.CURRENCY_CODE = FVVB.VALUE
    AND FVVB.ATTRIBUTE_CATEGORY = 'CO_Monedas_PO'
    LEFT JOIN FND_VS_VALUES_TL FVVTL ON FVVB.VALUE_ID = FVVTL.VALUE_ID
    AND FVVTL.LANGUAGE = 'E'
    LEFT JOIN IBY_EXTERNAL_PAYEES_ALL E ON PSV.PARTY_ID = E.PAYEE_PARTY_ID
    AND E.SUPPLIER_SITE_ID IS NULL
    AND E.PARTY_SITE_ID IS NULL
    LEFT JOIN IBY_EXT_PARTY_PMT_MTHDS F ON E.EXT_PAYEE_ID = F.EXT_PMT_PARTY_ID
    AND F.PRIMARY_FLAG = 'Y'
    LEFT JOIN IBY_PAYMENT_METHODS_TL G ON F.PAYMENT_METHOD_CODE = G.PAYMENT_METHOD_CODE
    AND G.LANGUAGE = 'E'