SELECT C.ORGANIZATION_ID,
    C.INVENTORY_ITEM_ID,
    --C.CATEGORY_ID,
    --ECT.CATEGORY_NAME,
    --ECSB.CATALOG_CODE
    max(
        case
            ECSB.CATALOG_CODE
            when 'CAT_COMPRAS' then ECT.CATEGORY_NAME
        end
    ) as CAT_COMPRAS,
    max(
        case
            ECSB.CATALOG_CODE
            when 'CAT_INVENTARIOS' then ECT.CATEGORY_NAME
        end
    ) as CAT_INVENTARIOS,
    max(
        case
            ECSB.CATALOG_CODE
            when 'CAT_COSTOS' then ECT.CATEGORY_NAME
        end
    ) as CAT_COSTOS
FROM --ARTICULOS ART,
    EGP_ITEM_CATEGORIES C,
    EGP_CATEGORIES_TL ECT,
    EGP_CATEGORY_SETS_B ECSB
WHERE 1 = 1 --AND ART.ORGANIZATION_ID = C.ORGANIZATION_ID (+)
    AND C.ORGANIZATION_ID IN (:P_ORGANIZATION)       
    --AND C.ORGANIZATION_ID IN ('300000003087000', '300000003102614') 
    --AND ART.INVENTORY_ITEM_ID = C.INVENTORY_ITEM_ID (+)
    AND C.CATEGORY_ID = ECT.CATEGORY_ID (+)
    AND ECT.LANGUAGE = 'US'
    AND C.CATEGORY_SET_ID = ECSB.CATEGORY_SET_ID(+)
GROUP BY C.ORGANIZATION_ID,
    C.INVENTORY_ITEM_ID --C.CATEGORY_ID,
    --ECT.CATEGORY_NAME,
    --ECSB.CATALOG_CODE