WITH ONHAND AS (
    SELECT Q.INVENTORY_ITEM_ID,
        Q.ORGANIZATION_ID,
        Q.SUBINVENTORY_CODE,
        LOC.SEGMENT1,
        SER.SERIAL_NUMBER,
        Q.LOT_NUMBER,
        SUM(Q.PRIMARY_TRANSACTION_QUANTITY) CANTIDAD
    FROM INV_ONHAND_QUANTITIES_DETAIL Q,
        INV_SERIAL_NUMBERS SER,
        INV_ITEM_LOCATIONS LOC
    WHERE 1 = 1
        /*AND Q.INVENTORY_ITEM_ID IN (
         '100000002954640',
         '100000002182532',
         '100000002167475'
         )*/
        AND Q.ORGANIZATION_ID IN (:P_ORGANIZATION)
        AND Q.INVENTORY_ITEM_ID = SER.INVENTORY_ITEM_ID (+)
        AND Q.ORGANIZATION_ID = SER.CURRENT_ORGANIZATION_ID (+)
        AND Q.CREATE_TRANSACTION_ID = SER.LAST_TRANSACTION_ID (+)
        AND Q.LOCATOR_ID = LOC.INVENTORY_LOCATION_ID(+)
        AND Q.ORGANIZATION_ID = LOC.ORGANIZATION_ID (+)
    GROUP BY Q.INVENTORY_ITEM_ID,
        Q.ORGANIZATION_ID,
        Q.SUBINVENTORY_CODE,
        LOC.SEGMENT1,
        SER.SERIAL_NUMBER,
        Q.LOT_NUMBER
),
ARTICULOS AS (
    SELECT A.ORGANIZATION_CODE,
        B.NAME ORGANIZATION,
        INV.ITEM_NUMBER ITEM,
        INV.DESCRIPTION DESCRIPTION_ITEM,
        UOMT.UNIT_OF_MEASURE,
        INV.ORGANIZATION_ID,
        INV.INVENTORY_ITEM_ID,
        INV.MIN_MINMAX_QUANTITY MINIMO,
        INV.MAX_MINMAX_QUANTITY MAXIMO,
        INV.LIST_PRICE_PER_UNIT,
        Q.SUBINVENTORY_CODE,
        Q.SEGMENT1,
        Q.SERIAL_NUMBER,
        Q.LOT_NUMBER,
        Q.CANTIDAD
    FROM EGP_SYSTEM_ITEMS INV,
        INV_UNITS_OF_MEASURE_TL UOMT,
        INV_UNITS_OF_MEASURE_B UOMB,
        INV_ORG_PARAMETERS A,
        HR_ORGANIZATION_UNITS_F_TL B,
        ONHAND Q
    WHERE 1 = 1
        AND B.ORGANIZATION_ID = INV.ORGANIZATION_ID
        AND A.ORGANIZATION_ID = INV.ORGANIZATION_ID
        AND UOMB.UOM_CODE = INV.PRIMARY_UOM_CODE
        AND UOMT.UNIT_OF_MEASURE_ID = UOMB.UNIT_OF_MEASURE_ID
        AND UOMT.LANGUAGE = 'US'
        AND B.LANGUAGE = 'US'
        AND Q.ORGANIZATION_ID = INV.ORGANIZATION_ID (+)
        AND Q.INVENTORY_ITEM_ID = INV.INVENTORY_ITEM_ID (+)
),
COSTO AS (
    SELECT DISTINCT ROUND(CPC.UNIT_COST_AVERAGE, 4) COSTO_TOTAL,
        CPC.COST_DATE,
        CPC.INVENTORY_ITEM_ID,
        ULT_COST.INVENTORY_ORG_ID,
        GL.SEGMENT2
    FROM CST_PERPAVG_COST CPC,
        (
            SELECT MAX(CPC.COST_DATE) COST_DATE,
                CPC.INVENTORY_ITEM_ID,
                CT.INVENTORY_ORG_ID,
                CPC.VAL_UNIT_ID,
                CPC.COST_BOOK_ID
            FROM CST_PERPAVG_COST CPC,
                CST_TRANSACTIONS CT,
                CST_COST_BOOKS_B CCB,
                (
                    SELECT ART.ORGANIZATION_ID,
                        ART.INVENTORY_ITEM_ID
                    FROM ARTICULOS ART
                    GROUP BY ART.ORGANIZATION_ID,
                        ART.INVENTORY_ITEM_ID
                ) ARTGP
            WHERE 1 = 1
                AND ARTGP.INVENTORY_ITEM_ID = CPC.INVENTORY_ITEM_ID (+)
                AND ARTGP.ORGANIZATION_ID = CT.INVENTORY_ORG_ID (+)
                AND CPC.TRANSACTION_ID = CT.TRANSACTION_ID
                AND CPC.COST_BOOK_ID = CCB.COST_BOOK_ID
                AND CCB.COST_BOOK_CODE = 'GCG_CST_LIB_NIIF'
            GROUP BY CPC.INVENTORY_ITEM_ID,
                CT.INVENTORY_ORG_ID,
                CPC.VAL_UNIT_ID,
                CPC.COST_BOOK_ID
        ) ULT_COST,
        CST_XLA_TRANSACTION_COSTS_V CSTXLA,
        CST_COST_DISTRIBUTION_LINES CSTCOS,
        GL_CODE_COMBINATIONS GL
    WHERE 1 = 1
        AND CPC.COST_DATE (+) = ULT_COST.COST_DATE
        AND CPC.INVENTORY_ITEM_ID = ULT_COST.INVENTORY_ITEM_ID
        AND CPC.VAL_UNIT_ID = ULT_COST.VAL_UNIT_ID
        AND CSTXLA.TRANSACTION_ID = CPC.TRANSACTION_ID
        AND CSTXLA.COST_ID = CSTCOS.COST_ID
        AND CSTCOS.ACCOUNTING_LINE_TYPE = 'INVENTORY_VALUATION'
        AND CSTCOS.SLA_CODE_COMBINATION_ID = GL.CODE_COMBINATION_ID
)
SELECT ART.*,
    CT.COSTO_TOTAL VALOR_UNITARIO,
    ROUND((ART.CANTIDAD * CT.COSTO_TOTAL), 3) VALOR_TOTAL,
    CT.COST_DATE,
    CT.SEGMENT2 CUENTA_CONTABLE
FROM ARTICULOS ART,
    COSTO CT
WHERE 1 = 1
    AND ART.ORGANIZATION_ID = CT.INVENTORY_ORG_ID (+)
    AND ART.INVENTORY_ITEM_ID = CT.INVENTORY_ITEM_ID (+)
